In [7]:
PREFIX="https://raw.githubusercontent.com/DataTalksClub/llm-zoomcamp/main"

In [10]:
!wget https://raw.githubusercontent.com/DataTalksClub/llm-zoomcamp/main/01-agentic-rag/code/ingest.py
!wget https://raw.githubusercontent.com/DataTalksClub/llm-zoomcamp/main/01-agentic-rag/code/rag_helper.py
!wget https://raw.githubusercontent.com/DataTalksClub/llm-zoomcamp/main/04-evaluation/code/evaluation_utils.py

--2026-07-22 17:29:27--  https://raw.githubusercontent.com/DataTalksClub/llm-zoomcamp/main/01-agentic-rag/code/ingest.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.110.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 738 [text/plain]
Saving to: ‘ingest.py.1’

ingest.py.1         100%[===================>]     738  --.-KB/s    in 0s

2026-07-22 17:29:28 (9.76 MB/s) - ‘ingest.py.1’ saved [738/738]

--2026-07-22 17:29:29--  https://raw.githubusercontent.com/DataTalksClub/llm-zoomcamp/main/01-agentic-rag/code/rag_helper.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.111.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2134 (2.1K) [text/plain]
Saving to: ‘rag_helper.py’

rag_helper.py       100%[===================>]   2.08K  --.-KB/s    in 0s

2026-07-22 17:29:30 (7.90 MB/s) - ‘rag_helper.py’ saved [2134/2134]

--2026-07-22 17:29:31--  https://raw.githubusercontent.com/DataTalksClub/llm-zoomcamp/main/04-evaluation/code/evaluation_utils.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.108.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3073 (3.0K) [text/plain]
Saving to: ‘evaluation_utils.py’

evaluation_utils.py 100%[===================>]   3.00K  --.-KB/s    in 0s

2026-07-22 17:29:32 (12.5 MB/s) - ‘evaluation_utils.py’ saved [3073/3073]

In [13]:
from ingest import load_faq_data
documents = load_faq_data()

In [15]:
documents_llm = []

for doc in documents:
    if doc["course"] == "llm-zoomcamp":
        documents_llm.append(doc)

len(documents_llm)

118

In [16]:
documents = documents_llm

In [17]:
doc = documents[0]
print(doc["id"])
print(doc["question"])
print(doc["answer"])

74eb249bbf
I just discovered the course. Can I still join?
Yes, but if you want to receive a certificate, you need to submit your project while we’re still accepting submissions.

In [19]:
from pydantic import BaseModel

class Questions(BaseModel):
    questions: list[str]

In [20]:
data_gen_instructions = """
You emulate a student who's taking our course.
Formulate 5 questions this student might ask based on a FAQ record. The record
should contain the answer to the questions, and the questions should be complete and not too short.
If possible, use as fewer words as possible from the record.

The output should resemble how people ask questions
on the internet. Not too formal, not too short, not too long.
""".strip()

- We ask the LLM to use different wording from the original document. This makes the evaluation more realistic - real users won't phrase their questions the same way as the FAQ.

In [28]:
import os 
from dotenv import load_dotenv
from openai import OpenAI

load_dotenv()
openai_client = OpenAI(
    api_key=os.getenv("GROQ_API_KEY"),
    base_url="https://api.groq.com/openai/v1"
)
llm_model = "openai/gpt-oss-20b"

In [29]:
import json

user_prompt = json.dumps(doc)

In [30]:
user_prompt

'{"id": "74eb249bbf", "course": "llm-zoomcamp", "section": "General Course-Related Questions", "question": "I just discovered the course. Can I still join?", "answer": "Yes, but if you want to receive a certificate, you need to submit your project while we\\u2019re still accepting submissions."}'

In [31]:
messages = [
    {"role": "developer", "content": data_gen_instructions},
    {"role": "user", "content": user_prompt}
]

In [32]:
response = openai_client.responses.parse(
    model=llm_model,
    input=messages,
    text_format=Questions
)

In [33]:
result = response.output_parsed

print(result)

questions=['Can I still enroll after seeing the course recently?', 'If I join late, can I still earn the certificate?', 'What’s the deadline to submit the final project for certification?', 'Do late registrants need to finish the project before a specific date?', 'Is it possible to get the certificate if I submit the project after enrollment?']

In [34]:
print(result.questions)

['Can I still enroll after seeing the course recently?', 'If I join late, can I still earn the certificate?', 'What’s the deadline to submit the final project for certification?', 'Do late registrants need to finish the project before a specific date?', 'Is it possible to get the certificate if I submit the project after enrollment?']

In [37]:
from evaluation_utils import llm_structured

result, usage = llm_structured(
    openai_client,
    data_gen_instructions,
    user_prompt,
    Questions,
    model=llm_model,
)

print(result.questions)

['Can I still enroll now that I’ve found out about the course?', 'If I join late, can I still earn a certificate?', 'How do I submit my project to qualify for a certificate?', 'What’s the deadline for submitting the final project for certification?', 'Will I be awarded a certificate if I finish the project after the deadline?']

In [38]:
usage.input_tokens, usage.output_tokens

(336, 731)

In [39]:
from evaluation_utils import calc_price

In [40]:
cost = calc_price(usage)

cost

{'input_cost': 0.000252, 'output_cost': 0.0032895, 'total_cost': 0.0035415}

In [41]:
records = []

for q in result.questions:
    records.append({
        "question": q,
        "document": doc["id"]
    })

records

[{'question': 'Can I still enroll now that I’ve found out about the course?',
  'document': '74eb249bbf'},
 {'question': 'If I join late, can I still earn a certificate?',
  'document': '74eb249bbf'},
 {'question': 'How do I submit my project to qualify for a certificate?',
  'document': '74eb249bbf'},
 {'question': 'What’s the deadline for submitting the final project for certification?',
  'document': '74eb249bbf'},
 {'question': 'Will I be awarded a certificate if I finish the project after the deadline?',
  'document': '74eb249bbf'}]

## Generating Ground Truth for All Documents

In [42]:
!pipenv install tqdm pandas

Loading .env environment variables...
Courtesy Notice:
Pipenv found itself running within a virtual environment,  so it will
automatically use that environment, instead of  creating its own for any
project. You can set
PIPENV_IGNORE_VIRTUALENVS=1 to force pipenv to ignore that environment and
create  its own instead.
You can set PIPENV_VERBOSITY=-1 to suppress this warning.
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
Installing tqdm...
✔ Installation Succeeded
Installing pandas...
✔ Installation Succeeded
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
Installing dependencies from Pipfile.lock (03e986)...
All dependencies are now up-to-date!
Upgrading tqdm, pandas in  dependencies.
Building requirements...
Resolving dependencies....
✔ Success! Locking packages...
⠼ Locking packages...Warning: WARNING:pipenv.patched.pip._vendor.urllib3.connectionpool:Connection pool is full, discarding connection: pypi.org. Connection pool size: 10
WARNING:pipenv.patched.pip._vendor.urllib3.connectionpool:Connection pool is full, discarding connection: pypi.org. Connection pool size: 10
WARNING:pipenv.patched.pip._vendor.urllib3.connectionpool:Connection pool is full, discarding connection: pypi.org. Connection pool size: 10
WARNING:pipenv.patched.pip._vendor.urllib3.connectionpool:Connection pool is full, discarding connection: pypi.org. Connection pool size: 10
WARNING:pipenv.patched.pip._vendor.urllib3.connectionpool:Connection pool is full, discarding connection: pypi.org. Connection pool size: 10
WARNING:pipenv.patched.pip._vendor.urllib3.connectionpool:Connection pool is full, discarding connection: pypi.org. Connection pool size: 10
⠼ Locking packages...
Building requirements...
Resolving dependencies....
✔ Success! Locking packages...
⠸ Locking packages...
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
Installing dependencies from Pipfile.lock (f18ca5)...
All dependencies are now up-to-date!
Installing dependencies from Pipfile.lock (f18ca5)...

In [43]:
from evaluation_utils import llm_structured_retry

In [44]:
def generate_ground_truth(doc):
    user_prompt = json.dumps(doc)

    out, usage = llm_structured_retry(
        openai_client,
        data_gen_instructions,
        user_prompt,
        Questions,
        model=llm_model
    )

    results = []

    for q in out.questions:
        results.append({
            "question": q,
            "document": doc["id"]
        })

    return results, usage

In [45]:
from tqdm.auto import tqdm

ground_truth = []
usages = []

for doc in tqdm(documents[:5]):
    records, usage = generate_ground_truth(doc)
    ground_truth.extend(records)
    usages.append(usage)

  0%|          | 0/5 [00:00<?, ?it/s]

## Parallel processing

In [47]:
from concurrent.futures import ThreadPoolExecutor
from evaluation_utils import map_progress

# This submits one job per document, updates the progress bar when a job finishes, and collects the results.

In [48]:
with ThreadPoolExecutor(max_workers=6) as pool:
    results = map_progress(pool, documents, generate_ground_truth)

  0%|          | 0/118 [00:00<?, ?it/s]

RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `openai/gpt-oss-20b` in organization `org_01ks7h6m1ffk3tt9zb0yx6496w` service tier `on_demand` on tokens per minute (TPM): Limit 8000, Used 7220, Requested 835. Please try again in 412.5ms. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

In [ ]:
ground_truth = []
usages = []

for records, usage in results:
    ground_truth.extend(records)
    usages.append(usage)

len(ground_truth)

In [ ]:
from evaluation_utils import calc_price

total_cost = 0.0

for usage in usages:
    cost = calc_price(usage)
    total_cost = total_cost + cost["total_cost"]

total_cost

In [ ]:
from evaluation_utils import calc_total_price

calc_total_price(usages)

In [ ]:
import pandas as pd

df_ground_truth = pd.DataFrame(ground_truth)

In [ ]:
df_ground_truth.to_csv("data/ground_truth-new.csv", index=False)

In [ ]:
# PREFIX=https://raw.githubusercontent.com/DataTalksClub/llm-zoomcamp/main

# wget -O data/ground_truth-new.csv ${PREFIX}/04-evaluation/data/ground_truth-new.csv
!cp "/home/hsu/Documents/Learning/llm-zoomcamp/04-evaluation/data/ground_truth-new.csv" groud_truth-new.csv

In [57]:
!pwd

/home/hsu/Documents/Learning/llm-zoomcamp-hw/module_4

                                            question    document
0  Is it okay to join the course late if I just f...  74eb249bbf
1  Can I still take this course even if I missed ...  74eb249bbf
2  If I join after the course has already started...  74eb249bbf
3  Do I need to submit my project before submissi...  74eb249bbf
4  I’m a bit late to the course—what do I need to...  74eb249bbf

## Search Evaluation

In [ ]:
import pandas as pd

df_ground_truth = pd.read_csv('data/ground_truth-new.csv')
df_ground_truth.head()

                                            question    document
0  Is it okay to join the course late if I just f...  74eb249bbf
1  Can I still take this course even if I missed ...  74eb249bbf
2  If I join after the course has already started...  74eb249bbf
3  Do I need to submit my project before submissi...  74eb249bbf
4  I’m a bit late to the course—what do I need to...  74eb249bbf

In [61]:
ground_truth = df_ground_truth.to_dict(orient="records")
ground_truth

[{'question': 'Is it okay to join the course late if I just found it now?',
  'document': '74eb249bbf'},
 {'question': 'Can I still take this course even if I missed the start date?',
  'document': '74eb249bbf'},
 {'question': 'If I join after the course has already started, am I still eligible for a certificate?',
  'document': '74eb249bbf'},
 {'question': 'Do I need to submit my project before submissions close to get the certificate?',
  'document': '74eb249bbf'},
 {'question': 'I’m a bit late to the course—what do I need to do to still earn the certificate?',
  'document': '74eb249bbf'},
 {'question': 'I registered for the LLM Zoomcamp — when should I expect a confirmation email?',
  'document': '977bf7786c'},
 {'question': 'Do I actually need an acceptance email before I can start the course and hand in homework?',
  'document': '977bf7786c'},
 {'question': 'If I filled out the registration form, does that mean I’m officially on a checked list for the course?',
  'document': '977bf7786c'},
 {'question': 'Is registering for the LLM Zoomcamp required, or is it just for estimating interest before the course starts?',
  'document': '977bf7786c'},
 {'question': 'Can I begin learning and submit homework even if I never got any email after signing up?',
  'document': '977bf7786c'},
 {'question': 'How do I join the Office Hours or live workshop if I don’t have the Zoom link?',
  'document': '489dd1c9d9'},
 {'question': 'Where can I watch the live sessions for the course, and how do I ask questions during them?',
  'document': '489dd1c9d9'},
 {'question': 'Is the Zoom link for the workshop shared with students, or only with the teaching team?',
  'document': '489dd1c9d9'},
 {'question': 'What’s the best way to follow the live Office Hours stream if I’m a student?',
  'document': '489dd1c9d9'},
 {'question': 'Should I type my questions in the live chat during Office Hours, or use something else?',
  'document': '489dd1c9d9'},
 {'question': 'How do the free GPU hours work on these cloud options — is the limit monthly, weekly, or something else?',
  'document': 'c6c2888275'},
 {'question': 'If I change the setup or configuration, does that affect the free GPU quota or get billed separately?',
  'document': 'c6c2888275'},
 {'question': 'What are some good free or low-cost cloud alternatives with GPU for this course besides the usual ones?',
  'document': 'c6c2888275'},
 {'question': 'Can I use Google Colab, Kaggle, or Databricks for the course notebooks and GPU tasks?',
  'document': 'c6c2888275'},
 {'question': 'Are there any restrictions on what I can install on these free GPU platforms, and how do I check what’s included in the free plan?',
  'document': 'c6c2888275'},
 {'question': 'How do I find my row on the leaderboard if I can’t see my name right away?',
  'document': 'c2903069a0'},
 {'question': 'Why does the leaderboard show some random nickname instead of my real name?',
  'document': 'c2903069a0'},
 {'question': 'Where can I check what display name I’m using for the course?',
  'document': 'c2903069a0'},
 {'question': 'Can I change the name that appears publicly, like to my Slack or GitHub name?',
  'document': 'c2903069a0'},
 {'question': 'What should I put in the profile fields so my certificate doesn’t use the default random name?',
  'document': 'c2903069a0'},
 {'question': 'Can I do the course at my own pace and still get a certificate at the end?',
  'document': '69d122f12e'},
 {'question': 'If I take the self-paced version, is there any way to earn the course certificate?',
  'document': '69d122f12e'},
 {'question': 'Do certificates only count for people who finish with the live cohort?',
  'document': '69d122f12e'},
 {'question': 'Why doesn’t the self-paced mode come with a certificate?',
  'document': '69d122f12e'},
 {'question': 'Is peer-review of the capstone project required in order to receive the certificate?',
  'document': '69d122f12e'},
 {'question': 'Can I still get the certificate if I skipped the first homework?',
  'document': '9f689c185f'},
 {'question': 'Do I have to do all the homework to receive the certificate for this course?',
  'document': '9f689c185f'},
 {'question': 'What do I actually need to pass in order to get the certificate?',
  'document': '9f689c185f'},
 {'question': 'Is homework mandatory, or is it just optional practice for the course?',
  'document': '9f689c185f'},
 {'question': "If homework isn't required, does it still affect anything like my ranking or points?",
  'document': '9f689c185f'},
 {'question': 'Why does the homework content keep changing in this course?',
  'document': '96286b4be4'},
 {'question': 'Is the material already finalized, or can it still change later?',
  'document': '96286b4be4'},
 {'question': 'If I start working on the homework now, could the final version be different?',
  'document': '96286b4be4'},
 {'question': 'How will I know when a module is actually ready and settled?',
  'document': '96286b4be4'},
 {'question': 'Is it safe to do the course work in advance, or should I wait until updates are announced?',
  'document': '96286b4be4'},
 {'question': 'When is the next time this course will be offered?',
  'document': 'bd31146b0e'},
 {'question': 'Do you know when the next course session starts?',
  'document': 'bd31146b0e'},
 {'question': 'Will there be another run of this course, and if so, when?',
  'document': 'bd31146b0e'},
 {'question': "What's the next scheduled offering for this course?",
  'document': 'bd31146b0e'},
 {'question': 'Can you tell me when the course is coming back?',
  'document': 'bd31146b0e'},
 {'question': 'Where can I find the course lectures or videos for this class?',
  'document': '31456f4b5f'},
 {'question': 'Are the recordings or lecture videos posted somewhere I can watch them?',
  'document': '31456f4b5f'},
 {'question': 'I’m looking for the videos—should I check the bookmarks or pinned links?',
  'document': '31456f4b5f'},
 {'question': 'Is there a specific YouTube channel for the course lectures?',
  'document': '31456f4b5f'},
 {'question': 'Where are the lecture videos linked, and what should I check first?',
  'document': '31456f4b5f'},
 {'question': 'Why does WSL2 say the model needs more memory even though my PC has enough RAM?',
  'document': 'f3dd94f323'},
 {'question': 'How can I increase the RAM available to WSL2 on Windows for running a model?',
  'document': 'f3dd94f323'},
 {'question': 'Where should I put a .wslconfig file to give WSL2 more memory?',
  'document': 'f3dd94f323'},
 {'question': 'What do I need to write in .wslconfig to set WSL2 memory to 8GB?',
  'document': 'f3dd94f323'},
 {'question': 'After changing WSL2 memory settings, how can I check if the new RAM limit is actually applied?',
  'document': 'f3dd94f323'},
 {'question': 'Why do I get a 500 server error when I try to log into the homework site with GitHub?',
  'document': 'c774542f32'},
 {'question': 'I see a third-party login failure on the course page — is GitHub login broken right now?',
  'document': 'c774542f32'},
 {'question': 'What should I do if GitHub sign-in fails while submitting homework?',
  'document': 'c774542f32'},
 {'question': 'Is there a workaround for the GitHub login error on the homework portal?',
  'document': 'c774542f32'},
 {'question': 'Does the GitHub login issue affect everyone, or can I use another account to submit?',
  'document': 'c774542f32'},
 {'question': "Why aren't we using LangChain in this course, and what should we learn first instead?",
  'document': 'b7cdde6b25'},
 {'question': 'Is there a reason the course skips LangChain for now?',
  'document': 'b7cdde6b25'},
 {'question': 'Why start without a framework like LangChain when building LLM apps?',
  'document': 'b7cdde6b25'},
 {'question': 'Should I learn the basics before using LangChain, and why?',
  'document': 'b7cdde6b25'},
 {'question': 'What’s the idea behind not using LangChain in the course material?',
  'document': 'b7cdde6b25'},
 {'question': 'Why do I get an OpenAI API error about insufficient credits when I run `chat.completions.create`?',
  'document': 'f5df151c59'},
 {'question': 'What does the OpenAI "Insufficient credits" message mean in `chat.completions.create`?',
  'document': 'f5df151c59'},
 {'question': 'I’m seeing an OpenAI API error about credits when testing chat completions — what should I check?',
  'document': 'f5df151c59'},
 {'question': 'Is the `OpenAI API Error: Insufficient credits` issue caused by my `chat.completions.create` call?',
  'document': 'f5df151c59'},
 {'question': 'What’s the reason for the credit-related error when using OpenAI chat completions?',
  'document': 'f5df151c59'},
 {'question': 'Why am I getting a 429 RateLimitError from OpenAI even though my code looks fine?',
  'document': '152af39a53'},
 {'question': 'Does OpenAI API have any free quota for this kind of request, or do I need to pay first?',
  'document': '152af39a53'},
 {'question': 'I added billing but still get an insufficient_quota error — do I need to make a new API key?',
  'document': '152af39a53'},
 {'question': 'Which model should I use in chat.completions.create if my current one is not available to my account?',
  'document': '152af39a53'},
 {'question': 'What are the exact steps to fix the OpenAI quota error and get my request working again?',
  'document': '152af39a53'},
 {'question': "Why am I getting 'Cannot import name OpenAI from openai' when I try to use the OpenAI client?",
  'document': '35e1ef85a1'},
 {'question': 'How do I fix the OpenAI import error in the course project?',
  'document': '35e1ef85a1'},
 {'question': "Do I need to upgrade the openai package if OpenAI can't be imported from openai?",
  'document': '35e1ef85a1'},
 {'question': "What version of openai should I use to avoid the 'Cannot import name OpenAI' error?",
  'document': '35e1ef85a1'},
 {'question': "My code breaks with 'Cannot import name OpenAI from openai' — what should I change?",
  'document': '35e1ef85a1'},
 {'question': 'How much do I need to spend to start using the OpenAI API?',
  'document': '554d0eb78b'},
 {'question': 'Is it expensive to use the OpenAI API for this course?',
  'document': '554d0eb78b'},
 {'question': 'Do I have to put in a lot of money before I can try the OpenAI API?',
  'document': '554d0eb78b'},
 {'question': 'What is the minimum top-up amount for the OpenAI API?',
  'document': '554d0eb78b'},
 {'question': 'Can I get started with OpenAI API usage for just a few cents?',
  'document': '554d0eb78b'},
 {'question': 'Do I need to pay for the OpenAI API to finish the homework in this course, or are there free options I can use instead?',
  'document': '85384a18e5'},
 {'question': 'For the LLM Zoomcamp assignments, is a paid OpenAI subscription required, or can I rely on the free alternatives from the course repo?',
  'document': '85384a18e5'},
 {'question': 'Can I complete the course tasks without buying OpenAI API access, and where are the no-cost alternatives listed?',
  'document': '85384a18e5'},
 {'question': 'Is paying for OpenAI necessary for the homeworks, or does the GitHub have some free API alternatives I can use?',
  'document': '85384a18e5'},
 {'question': 'To do the course exercises, do I have to subscribe to OpenAI, or is there a list of free replacements somewhere in the course materials?',
  'document': '85384a18e5'},
 {'question': 'How can I keep my API keys safe in a project without putting them in the notebook or code?',
  'document': '8d23fe792f'},
 {'question': "What's a simple way to save several API keys locally so I can load them later in Python?",
  'document': '8d23fe792f'},
 {'question': "How do I set up a YAML file for my OpenAI and Groq keys and make sure Git doesn't track it?",
  'document': '8d23fe792f'},
 {'question': 'Which package do I need if I want to read API keys from a YAML file in a Jupyter notebook?',
  'document': '8d23fe792f'},
 {'question': 'Can I load my secret keys from a file and use them directly instead of using environment variables?',
  'document': '8d23fe792f'},
 {'question': 'How do I keep my API key in a .env file and read it in Python?',
  'document': '233dabe430'},
 {'question': 'What imports do I need to load environment variables from a .env file?',
  'document': '233dabe430'},
 {'question': 'How can I point Python to the right .env path and get the key value?',
  'document': '233dabe430'},
 {'question': "What's the easiest way to access API_KEY_abc after loading .env?",
  'document': '233dabe430'},
 {'question': 'Do I need to add my .env file to .gitignore, and why?',
  'document': '233dabe430'},
 {'question': 'Why does my OPENAI_API_KEY keep showing as missing inside Jupyter, and how do I fix it?',
  'document': '86d99bbf21'},
 {'question': 'If I already put the key in a .envrc file, why is the notebook still throwing the api_key error?',
  'document': '86d99bbf21'},
 {'question': 'What’s the easiest way to make OpenAI API auth work in a notebook when direnv isn’t enough?',
  'document': '86d99bbf21'},
 {'question': 'How do I use python-dotenv to load my environment variables from .envrc in Jupyter?',
  'document': '86d99bbf21'},
 {'question': 'Can I store OPENAI_API_KEY in GitHub Codespaces instead of setting it locally, and how do I do that?',
  'document': '86d99bbf21'},
 {'question': 'How can I figure out the GPT-4o token count for homework 6 if I’m using Groq and there’s no tokenizer for it?',
  'document': 'fe8fed31e6'},
 {'question': 'Do I need an OpenAI API key just to check how many tokens a prompt has in this assignment?',
  'document': 'fe8fed31e6'},
 {'question': 'What library should I use to estimate the number of OpenAI tokens in question 6?',
  'document': 'fe8fed31e6'},
 {'question': 'Is there a way to count GPT-4o tokens without using the OpenAI API itself?',
  'document': 'fe8fed31e6'},
 {'question': 'If Groq doesn’t have a tokenizer, what’s the simplest way to get the token number the homework wants?',
  'document': 'fe8fed31e6'},
 {'question': 'Can I swap OpenAI for Groq in the course exercises and final project?',
  'document': 'ee43413718'},
 {'question': 'Is it okay to use a different LLM platform instead of OpenAI for the homework?',
  'document': 'ee43413718'},
 {'question': 'Do I need a paid API like OpenAI to finish the assignments, or can I run everything locally?',
  'document': 'ee43413718'},
 {'question': 'If I use another model provider, will I have to change the code myself?',
  'document': 'ee43413718'},
 {'question': 'Where should I look if I want to adapt the project to a platform like Groq?',
  'document': 'ee43413718'},
 {'question': 'Can I use open-source alternatives instead of the OpenAI API for this course?',
  'document': '3fd5c51182'},
 {'question': 'Where can I find the list of OpenAI alternatives mentioned in Module 1?',
  'document': '3fd5c51182'},
 {'question': 'Is it okay to follow the course using an open-source LLM API rather than OpenAI?',
  'document': '3fd5c51182'},
 {'question': 'Does the course support non-OpenAI options, and where is that covered?',
  'document': '3fd5c51182'},
 {'question': 'What should I check if I want to use an open-source replacement for OpenAI in the intro module?',
  'document': '3fd5c51182'},
 {'question': 'Why am I getting RateLimitError 429 with insufficient_quota on OpenAI even though I’m not sending many requests?',
  'document': '6e1d8a7b29'},
 {'question': 'Does insufficient_quota mean I just need to wait and retry later, or is something wrong with my account?',
  'document': '6e1d8a7b29'},
 {'question': 'My OpenAI API calls fail because of no credit — what’s the quickest fix to get the course working again?',
  'document': '6e1d8a7b29'},
 {'question': 'Can I use a free alternative instead of paying for OpenAI credit, and which ones work with the course?',
  'document': '6e1d8a7b29'},
 {'question': 'What model or provider should I switch to if I want to avoid the quota error without adding money to OpenAI?',
  'document': '6e1d8a7b29'},
 {'question': 'Why does my homework query return an empty list after filtering, even though the data is there?',
  'document': '83da208a64'},
 {'question': 'What am I missing if my Q3 filter gives no results in the LLM Zoomcamp homework?',
  'document': '83da208a64'},
 {'question': 'Could this be an indexing problem if the search comes back empty after I apply the filter?',
  'document': '83da208a64'},
 {'question': 'Do I need to set up the index differently before loading the data for this assignment?',
  'document': '83da208a64'},
 {'question': 'How should I fix the empty results issue in HW Q3 when using filters and queries?',
  'document': '83da208a64'},
 {'question': 'Why am I getting a SyntaxError about an invalid character when I run the minsearch file I downloaded?',
  'document': 'f3a92e7c81'},
 {'question': 'Did I probably save the GitHub page instead of the actual Python source for minsearch?',
  'document': 'f3a92e7c81'},
 {'question': 'What’s the right way to download minsearch from GitHub so I can run it without that weird character error?',
  'document': 'f3a92e7c81'},
 {'question': 'Is there a better way to install minsearch than copying the file from GitHub by hand?',
  'document': 'f3a92e7c81'},
 {'question': 'Should I use pip or uv to install minsearch instead of downloading the raw code?',
  'document': 'f3a92e7c81'},
 {'question': 'Why do I get ModuleNotFoundError when I try to import docx in parse-faq.ipynb?',
  'document': 'cf93377279'},
 {'question': 'Is the package name for docx actually python-docx?',
  'document': 'cf93377279'},
 {'question': 'What should I install if import docx keeps failing in the notebook?',
  'document': 'cf93377279'},
 {'question': 'How do I fix the docx import issue in parse-faq.ipynb?',
  'document': 'cf93377279'},
 {'question': 'Do I need to pip install python-docx instead of docx?',
  'document': 'cf93377279'},
 {'question': 'How can I check token usage for Gemini, Mistral, or Hugging Face models if tiktoken is really meant for OpenAI only?',
  'document': '4d8c1f5b3a'},
 {'question': 'Is it okay to use cl100k_base as a fallback tokenizer for other LLM providers when I want an estimate?',
  'document': '4d8c1f5b3a'},
 {'question': 'What is the recommended way to count tokens in Gemini with the official SDK?',
  'document': '4d8c1f5b3a'},
 {'question': 'How do I get token counts for open-source models like Llama using Transformers?',
  'document': '4d8c1f5b3a'},
 {'question': 'Which tokenizer should I use for Mistral instead of trying to rely on OpenAI-style token counting?',
  'document': '4d8c1f5b3a'},
 {'question': 'Why do I get a different token count in tiktoken than what OpenAI shows in the API response?',
  'document': 'bf0403d21b'},
 {'question': 'How come my prompt has 320 tokens locally, but OpenAI says 327 for the same request?',
  'document': 'bf0403d21b'},
 {'question': 'Does chat.completions.create add extra tokens beyond the text I send?',
  'document': 'bf0403d21b'},
 {'question': 'What makes OpenAI count more tokens than just encoding the visible message content?',
  'document': 'bf0403d21b'},
 {'question': 'Can whitespace, newlines, or weird Unicode characters change the token total in OpenAI chat requests?',
  'document': 'bf0403d21b'},
 {'question': 'How can I set my API key once so I don’t have to export it in every new terminal?',
  'document': '8b2f5e9d04'},
 {'question': 'Is there a way to make env vars load automatically when I enter a project folder?',
  'document': '8b2f5e9d04'},
 {'question': 'What’s the easiest setup for keeping my OpenAI key in a project without putting it in the code?',
  'document': '8b2f5e9d04'},
 {'question': 'How should I handle API keys in GitHub Codespaces so they aren’t stored in the repo?',
  'document': '8b2f5e9d04'},
 {'question': 'If I’m running Python scripts, what can I use to load a .env file automatically?',
  'document': '8b2f5e9d04'},

In [62]:
from ingest import load_faq_data, build_index

documents = load_faq_data()

documents_llm = []

for doc in documents:
    if doc["course"] == "llm-zoomcamp":
        documents_llm.append(doc)

documents = documents_llm
index = build_index(documents)

In [63]:
def text_search(query):
    boost_dict = {"question": 3.0, "section": 0.5}

    return index.search(
        query,
        num_results=5,
        boost_dict=boost_dict
    )

In [64]:
q = ground_truth[0]
q

{'question': 'Is it okay to join the course late if I just found it now?',
 'document': '74eb249bbf'}

In [65]:
doc_id = q["document"]
results = text_search(query=q["question"])

In [66]:
for d in results:
    print(f'{d["id"]} == {doc_id}: {d["id"] == doc_id}')

74eb249bbf == 74eb249bbf: True
0fab61eca2 == 74eb249bbf: False
610ccb23c0 == 74eb249bbf: False
977bf7786c == 74eb249bbf: False
acf8fa5356 == 74eb249bbf: False

In [67]:
relevance = []

for d in results:
    relevance.append(int(d["id"] == doc_id))

relevance

[1, 0, 0, 0, 0]

In [68]:
def compute_relevance_text(q):
    doc_id = q["document"]
    results = text_search(query=q["question"])

    relevance = []
    for d in results:
        relevance.append(int(d["id"] == doc_id))

    return relevance

In [69]:
q = ground_truth[0]
print(q["question"])
compute_relevance_text(q)
# [1, 0, 0, 0, 0]

Is it okay to join the course late if I just found it now?

[1, 0, 0, 0, 0]

In [70]:
q = ground_truth[11]
print(q["question"])
compute_relevance_text(q)
# [1, 0, 0, 0, 0]

Where can I watch the live sessions for the course, and how do I ask questions during them?

[1, 0, 0, 0, 0]

In [71]:
q = ground_truth[50]
print(q["question"])
compute_relevance_text(q)
# [1, 0, 0, 0, 0]

Why does WSL2 say the model needs more memory even though my PC has enough RAM?

[1, 0, 0, 0, 0]

In [72]:
from tqdm.notebook import tqdm

def compute_relevance_total_text(ground_truth):
    relevance_total = []

    for q in tqdm(ground_truth):
        relevance = compute_relevance_text(q)
        relevance_total.append(relevance)

    return relevance_total

In [73]:
ground_truth_sample = ground_truth[:15]
relevance_total_text = compute_relevance_total_text(ground_truth_sample)

  0%|          | 0/15 [00:00<?, ?it/s]

In [74]:
relevance_total_text

[[1, 0, 0, 0, 0],
 [0, 0, 1, 0, 0],
 [1, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0],
 [1, 0, 0, 0, 0],
 [0, 1, 0, 0, 0],
 [1, 0, 0, 0, 0],
 [1, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0],
 [1, 0, 0, 0, 0],
 [1, 0, 0, 0, 0],
 [1, 0, 0, 0, 0],
 [0, 1, 0, 0, 0]]

In [75]:
# generalize the search for whatever search function is provided
def compute_relevance(q, search_function):
    doc_id = q["document"]
    results = search_function(query=q["question"])

    relevance = []
    for d in results:
        relevance.append(int(d["id"] == doc_id))

    return relevance

In [76]:
def compute_relevance_total(ground_truth, search_function):
    relevance_total = []

    for q in tqdm(ground_truth):
        relevance = compute_relevance(q, search_function)
        relevance_total.append(relevance)

    return relevance_total

In [77]:
relevance_total = compute_relevance_total(ground_truth_sample, text_search)
relevance_total

  0%|          | 0/15 [00:00<?, ?it/s]

[[1, 0, 0, 0, 0],
 [0, 0, 1, 0, 0],
 [1, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0],
 [1, 0, 0, 0, 0],
 [0, 1, 0, 0, 0],
 [1, 0, 0, 0, 0],
 [1, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0],
 [1, 0, 0, 0, 0],
 [1, 0, 0, 0, 0],
 [1, 0, 0, 0, 0],
 [0, 1, 0, 0, 0]]

In [78]:
relevance_total = compute_relevance_total(ground_truth, text_search)

  0%|          | 0/395 [00:00<?, ?it/s]

## Search Evaluation Metrics

In [79]:
cnt = 0

for line in relevance_total:
    if 1 in line:
        cnt = cnt + 1

cnt

257

In [80]:
cnt / len(relevance_total)
# 0.933

0.6506329113924051

In [81]:
def hit_rate(relevance):
    cnt = 0

    for line in relevance:
        if 1 in line:
            cnt = cnt + 1

    return cnt / len(relevance)

In [83]:
hit_rate(relevance_total)

# This means that search found the correct document for 65.1% of the queries in this example.

0.6506329113924051

### Mean Reciprocal Rank (MRR)

In [84]:
total_score = 0.0

for line in relevance_total:
    for rank in range(len(line)):
        if line[rank] == 1:
            total_score = total_score + 1 / (rank + 1)
            break

total_score

226.14999999999998

use rank + 1 because Python counts positions from zero. The first position should score 1/1, and without the + 1 we'd divide by zero.

In [85]:
total_score / len(relevance_total)

0.5725316455696202


MRR is the average of these scores across all queries. It rewards systems that put the correct document near the top.

In [86]:
def mrr(relevance):
    total_score = 0.0

    for line in relevance:
        for rank in range(len(line)):
            if line[rank] == 1:
                total_score = total_score + 1 / (rank + 1)
                break

    return total_score / len(relevance)

In [87]:
mrr(relevance_total)

0.5725316455696202

In [88]:
def evaluate(ground_truth, search_function):
    relevance_total = compute_relevance_total(ground_truth, search_function)

    return {
        "hit_rate": hit_rate(relevance_total),
        "mrr": mrr(relevance_total),
    }

In [89]:
evaluate(
    ground_truth,
    text_search
)

  0%|          | 0/395 [00:00<?, ?it/s]

{'hit_rate': 0.6506329113924051, 'mrr': 0.5725316455696202}

# Search Parameter Tuning

In [90]:
def search_boost(query, question_boost):
    boost_dict = {"question": question_boost, "section": 0.5}

    return index.search(
        query,
        num_results=5,
        boost_dict=boost_dict,
    )

In [91]:
for boost in [0.5, 1.0, 3.0, 5.0, 10.0]:
    result = evaluate(
        ground_truth,
        lambda query, boost=boost: search_boost(query, boost)
    )
    print(f"boost={boost}: {result}")

  0%|          | 0/395 [00:00<?, ?it/s]

boost=0.5: {'hit_rate': 0.6860759493670886, 'mrr': 0.5862447257383967}

  0%|          | 0/395 [00:00<?, ?it/s]

boost=1.0: {'hit_rate': 0.6911392405063291, 'mrr': 0.5935864978902954}

  0%|          | 0/395 [00:00<?, ?it/s]

boost=3.0: {'hit_rate': 0.6506329113924051, 'mrr': 0.5725316455696202}

  0%|          | 0/395 [00:00<?, ?it/s]

boost=5.0: {'hit_rate': 0.6379746835443038, 'mrr': 0.5515611814345992}

  0%|          | 0/395 [00:00<?, ?it/s]

boost=10.0: {'hit_rate': 0.6253164556962025, 'mrr': 0.5332067510548525}

In [92]:
def search_boosts(query, question_boost, answer_boost, section_boost):
    boost_dict = {
        "question": question_boost,
        "section": section_boost,
        "answer": answer_boost,
    }

    return index.search(
        query,
        num_results=5,
        boost_dict=boost_dict,
    )

In [93]:
results = []

for question_boost in [1.0, 2.0, 5.0]:
    for answer_boost in [1.0, 2.0, 4.0, 10.0]:
        for section_boost in [0.1, 0.2, 0.5]:
            print(
                f"Evaluating question_boost={question_boost},"
                f" answer_boost={answer_boost},"
                f" section_boost={section_boost}..."
            )
            result = evaluate(
                ground_truth,
                lambda query, question_boost=question_boost, answer_boost=answer_boost, section_boost=section_boost: search_boosts(
                    query,
                    question_boost,
                    answer_boost,
                    section_boost
                )
            )

            results.append({
                "question": question_boost,
                "answer": answer_boost,
                "section": section_boost,
                "hit_rate": result["hit_rate"],
                "mrr": result["mrr"],
            })

Evaluating question_boost=1.0, answer_boost=1.0, section_boost=0.1...

  0%|          | 0/395 [00:00<?, ?it/s]

Evaluating question_boost=1.0, answer_boost=1.0, section_boost=0.2...

  0%|          | 0/395 [00:00<?, ?it/s]

Evaluating question_boost=1.0, answer_boost=1.0, section_boost=0.5...

  0%|          | 0/395 [00:00<?, ?it/s]

Evaluating question_boost=1.0, answer_boost=2.0, section_boost=0.1...

  0%|          | 0/395 [00:00<?, ?it/s]

Evaluating question_boost=1.0, answer_boost=2.0, section_boost=0.2...

  0%|          | 0/395 [00:00<?, ?it/s]

Evaluating question_boost=1.0, answer_boost=2.0, section_boost=0.5...

  0%|          | 0/395 [00:00<?, ?it/s]

Evaluating question_boost=1.0, answer_boost=4.0, section_boost=0.1...

  0%|          | 0/395 [00:00<?, ?it/s]

Evaluating question_boost=1.0, answer_boost=4.0, section_boost=0.2...

  0%|          | 0/395 [00:00<?, ?it/s]

Evaluating question_boost=1.0, answer_boost=4.0, section_boost=0.5...

  0%|          | 0/395 [00:00<?, ?it/s]

Evaluating question_boost=1.0, answer_boost=10.0, section_boost=0.1...

  0%|          | 0/395 [00:00<?, ?it/s]

Evaluating question_boost=1.0, answer_boost=10.0, section_boost=0.2...

  0%|          | 0/395 [00:00<?, ?it/s]

Evaluating question_boost=1.0, answer_boost=10.0, section_boost=0.5...

  0%|          | 0/395 [00:00<?, ?it/s]

Evaluating question_boost=2.0, answer_boost=1.0, section_boost=0.1...

  0%|          | 0/395 [00:00<?, ?it/s]

Evaluating question_boost=2.0, answer_boost=1.0, section_boost=0.2...

  0%|          | 0/395 [00:00<?, ?it/s]

Evaluating question_boost=2.0, answer_boost=1.0, section_boost=0.5...

  0%|          | 0/395 [00:00<?, ?it/s]

Evaluating question_boost=2.0, answer_boost=2.0, section_boost=0.1...

  0%|          | 0/395 [00:00<?, ?it/s]

Evaluating question_boost=2.0, answer_boost=2.0, section_boost=0.2...

  0%|          | 0/395 [00:00<?, ?it/s]

Evaluating question_boost=2.0, answer_boost=2.0, section_boost=0.5...

  0%|          | 0/395 [00:00<?, ?it/s]

Evaluating question_boost=2.0, answer_boost=4.0, section_boost=0.1...

  0%|          | 0/395 [00:00<?, ?it/s]

Evaluating question_boost=2.0, answer_boost=4.0, section_boost=0.2...

  0%|          | 0/395 [00:00<?, ?it/s]

Evaluating question_boost=2.0, answer_boost=4.0, section_boost=0.5...

  0%|          | 0/395 [00:00<?, ?it/s]

Evaluating question_boost=2.0, answer_boost=10.0, section_boost=0.1...

  0%|          | 0/395 [00:00<?, ?it/s]

Evaluating question_boost=2.0, answer_boost=10.0, section_boost=0.2...

  0%|          | 0/395 [00:00<?, ?it/s]

Evaluating question_boost=2.0, answer_boost=10.0, section_boost=0.5...

  0%|          | 0/395 [00:00<?, ?it/s]

Evaluating question_boost=5.0, answer_boost=1.0, section_boost=0.1...

  0%|          | 0/395 [00:00<?, ?it/s]

Evaluating question_boost=5.0, answer_boost=1.0, section_boost=0.2...

  0%|          | 0/395 [00:00<?, ?it/s]

Evaluating question_boost=5.0, answer_boost=1.0, section_boost=0.5...

  0%|          | 0/395 [00:00<?, ?it/s]

Evaluating question_boost=5.0, answer_boost=2.0, section_boost=0.1...

  0%|          | 0/395 [00:00<?, ?it/s]

Evaluating question_boost=5.0, answer_boost=2.0, section_boost=0.2...

  0%|          | 0/395 [00:00<?, ?it/s]

Evaluating question_boost=5.0, answer_boost=2.0, section_boost=0.5...

  0%|          | 0/395 [00:00<?, ?it/s]

Evaluating question_boost=5.0, answer_boost=4.0, section_boost=0.1...

  0%|          | 0/395 [00:00<?, ?it/s]

Evaluating question_boost=5.0, answer_boost=4.0, section_boost=0.2...

  0%|          | 0/395 [00:00<?, ?it/s]

Evaluating question_boost=5.0, answer_boost=4.0, section_boost=0.5...

  0%|          | 0/395 [00:00<?, ?it/s]

Evaluating question_boost=5.0, answer_boost=10.0, section_boost=0.1...

  0%|          | 0/395 [00:00<?, ?it/s]

Evaluating question_boost=5.0, answer_boost=10.0, section_boost=0.2...

  0%|          | 0/395 [00:00<?, ?it/s]

Evaluating question_boost=5.0, answer_boost=10.0, section_boost=0.5...

  0%|          | 0/395 [00:00<?, ?it/s]

In [94]:
df_results = pd.DataFrame(results)
df_results.sort_values("mrr", ascending=False).head(10)

    question  answer  section  hit_rate       mrr
34       5.0    10.0      0.2  0.754430  0.646540
18       2.0     4.0      0.1  0.754430  0.646203
33       5.0    10.0      0.1  0.751899  0.646034
3        1.0     2.0      0.1  0.749367  0.645105
35       5.0    10.0      0.5  0.749367  0.645105
19       2.0     4.0      0.2  0.749367  0.645105
4        1.0     2.0      0.2  0.746835  0.643080
20       2.0     4.0      0.5  0.746835  0.642236
7        1.0     4.0      0.2  0.746835  0.633460
6        1.0     4.0      0.1  0.746835  0.633249

In [95]:
def text_search(query):
    boost_dict = {
        "question": 1.0,
        "answer": 2.0,
        "section": 0.1,
    }

    return index.search(
        query,
        num_results=5,
        boost_dict=boost_dict,
    )